Repository gyanshankar1708/GrowCraft, pull requests merged in 2025-08, with the labels that each got.

#62 Darkmode added to contact page
  contact.html
  src/contact.css
  src/utils.js
Labels: gssoc2025, Level 3

#63 Fixed the color change on hover effect in the training link section in Dark Mode
  src/style.css
Labels: gssoc2025, Level 1

#67 Darkmode Button Alignment
  src/style.css
Labels: gssoc2025, Level 1

#72 UI Enhancement: Scroll-to-Top Button Redesigned for Better UX
  index.html
  src/style.css
Labels: gssoc2025, Level 1

#76 Added Blog section (#45)
  blogListing.html
  blogView.html
  blogWrite.html
  index.html
  src/blogView.js
  src/blogs.css
  src/blogs.js
  src/style.css
  src/write-blog.js
Labels: gssoc2025, Level 3

#79 🔧 Updated footer layout: centered 'About' and horizontal social links
  index.html
  src/style.css
Labels: gssoc2025, Level 3

#69 Seperated the files #51
  index.html
  src/script.js
  src/style.css
Labels: gssoc2025, Level 1

#87 Fixed Graphic Design Component-box Size
  index.html
  src/style.css
Labels: gssoc2025, Level 2

#97 Feature : Fully Responsive Website Development Page
  images/pexels-fauxels-3182773.jpg
  images/web-dev.png
  index.html
  src/contact.html
  src/css/style.css
  src/utils.js
  src/web.html
Labels: gssoc2025, Level 3

#102 Added License
  LICENSE
Labels: gssoc2025, Level 3

#98 Our Work section's , the Graphic Design section is now properly aligned with the other two sections span tags
  index.html
  src/style.css
Labels: gssoc2025, Level 1

#114 Updated README.md File for Better Project Documentation
  Readme.md
  images/index.png
  images/services.png
Labels: gssoc2025, Level 3

#121 Add “Explore” button & pad space between “Read More” and "Explore" buttons
  index.html
Labels: gssoc2025, Level 2

#130 Added working social media links
  index.html
Labels: gssoc2025, Level 1

#149 Enhanced Services Section with 2x2 Layout and Smooth Animations
  index.html
  src/script.js
  src/style.css
Labels: gssoc2025, Level 3

#143 Improved the UI of the footer
  index.html
Labels: gssoc2025, Level 2

#148 fix: center align navbar and gaps accordingly
  index.html
Labels: gssoc2025, level1

#164 Progressive Loading & Smooth Scroll Animations
  src/script.js
  src/style.css
Labels: gssoc2025, level2

#158 Perfectly Working dark mode light mode toggle switch
  blogListing.html
  blogView.html
  blogWrite.html
  index.html
  src/contact.html
  src/css/style.css
  src/darkMode.js
  src/login.html
  src/style.css
  src/utils.js
  src/web.html
  src/workList.html
  src/works.html
Labels: gssoc2025, level3

#186 Fix #180: Updated footer theme in workList.html
  src/workList.html
Labels: gssoc2025, level3

#189 fix: #152 – Enhance 'What We Made' and 'What We Offer' sections with modern card design, alignment improvements, and carousel upgrade
  src/web.html
Labels: gssoc2025, level3

#222 feat(ui): add responsive 'Get In Touch' section with proper layout an…
  src/contact.css
  src/contact.html
Labels: gssoc2025, level2

#232 Update contact.html
  src/contact.html
Labels: gssoc2025, level3

#247 Add Digital Marketing page
  src/digital-marketing.html
Labels: gssoc2025, level3

#230 solved Issue #195 add animation on about section and transparent background of logo
  images/logo_bg_transparent.png
  index.html
  src/style.css
Labels: gssoc2025, level2

#252 Fix: Add missing favicon on contact.html and implement sticky navbar …
  src/contact.html
Labels: gssoc2025, level1

#231 fix: improve UI for work section cards and footer
  index.html
  src/style.css
  src/workList.html
Labels: gssoc2025, level1

#260 Fix inconsistent logo styling
  blogListing.html
  blogView.html
  blogWrite.html
  images/logo-transparent-dark-mode.png
  index.html
  src/contact.html
  src/darkMode.js
  src/images/logo-transparent-dark-mode.png
  src/images/logo_bg_transparent.png
Labels: gssoc2025, level2

#273 button color contrast fix in services section
  index.html
Labels: gssoc2025, level1

#274 fix added for navbar link for web-dev page
  learn/webdev.html
Labels: gssoc2025, level1

#248 Navbar toggling fix
  images/Logo.png
  images/Logo_new.png
  index.html
Labels: gssoc2025, level3

#203 Bugfix: Proper redirect of Contact Us page favicon
  src/contact.html
Labels: gssoc2025, level1

#289 Navbar Styling & Alignment for Mobile View
  blogListing.html
  index.html
  src/contact.html
  src/style.css
  src/web.html
Labels: gssoc25, level2

#305 [Fix] Footer Year Auto-Update & Social Links Open in New Tab (#300)
  index.html
Labels: gssoc25, level1

#258 Added gradient styling and animation to Submit button
  src/contact.html
Labels: gssoc25, level3

#302 Feature Social Media Page
  index.html
  src/css/style.css
  src/social-media.html
  src/web.html
Labels: gssoc25, level3

#315 Enhance Contact Form: Phone Validation with Country Code & Future-Date Restriction (Replaces #257)
  src/contact.html
  src/css/style.css
  src/phone-validation.js
  src/phonevalidator.css
Labels: gssoc25, level2

#348 Fix Underline Issue in Training & Internship Program Section
  src/css/style.css
Labels: gssoc25, level1

#349 Fix Navbar & Logo Inconsistency on Digital Marketing Page
  src/digital-marketing.html
Labels: gssoc25, level1

#353 FEATURE : Add cyber threat services page
  index.html
  src/cyber-analyst.html
  src/darkMode.js
Labels: gssoc25, level3

#361 enhanced: Contributors section images not attached #359
  Readme.md
Labels: gssoc25, level2

#362 fixed: our work navigation fix
  index.html
Labels: gssoc25, level1

#374 Updated Footer Styling for Light/Dark Mode & Brand Consistency
  src/web.html
Labels: gssoc25, level2

#376 Updated Footer Styling on Social media Service Page for Light/Dark Mode
  src/cyber-analyst.html
  src/social-media.html
Labels: gssoc25, level2

#381 Fixed Previous & Next buttons in the Slide bar section
  src/style.css
Labels: gssoc25, level3

#383 🎉 Feature: Scroll-to-Top Functionality Across All Pages
  src/content-writing.html
  src/cyber-analyst.html
  src/graphic_design.html
  src/social-media.html
  src/web.html
Labels: gssoc25, level2

#389 Enhanced UI of Footer
  index.html
Labels: gssoc25, level1
