Repository gyanshankar1708/GrowCraft, pull requests merged in 2025-10, with the labels that each got.

#821 Fix: Restructure Footer on contact.html with Proper Columns and Responsive Design
  src/contact.html
Labels: gssoc25, level3, hacktoberfest-accepted

#825 Fix: Restructure Footer on work.html with Proper Columns and Responsive Design
  work.html
Labels: gssoc25, level2, hacktoberfest-accepted

#845 Implement Sitemap Page with Search and Responsive Design
  sitemap.html
Labels: gssoc25, level3, hacktoberfest-accepted

#776 Fixed the text color issue in cards of content writing page
  src/content-writing.html
Labels: gssoc25, level2, hacktoberfest-accepted

#814 Change phone input type from tel to number
  src/contact.html
Labels: gssoc25, level1, hacktoberfest-accepted

#823 Fix: Restructure Footer on work.html with Proper Columns and Responsive Design
  work.html
Labels: gssoc25, level3, hacktoberfest-accepted

#824 Added dedicated page for cyber-analyst
  learn/contentwriting.html
  learn/cyberanalyst.css
  learn/cyberanalyst.html
Labels: gssoc25, level3, hacktoberfest-accepted

#833 Made the links functional in FAQ page
  src/faq.html
Labels: gssoc25, level1, hacktoberfest-accepted

#854 get a free proposal and see our work tab links fixed
  src/digital-marketing.html
Labels: gssoc25, level1

#840 Add theme toggle (light/dark) to Contact page navbar with persistent preference
  src/contact.html
Labels: gssoc25, level3, hacktoberfest-accepted

#855 Fix work page navbar
  work.html
Labels: gssoc25, level2, hacktoberfest-accepted

#860 our work footer adjusted in full width
  work.html
Labels: gssoc25, level2, hacktoberfest-accepted

#878 [BUG FIX] Portfolio page is directed properly in footer section in di…
  src/digital-marketing.html
Labels: gssoc25, level1, hacktoberfest-accepted

#873 Added dark mode in webdev.html
  learn/webdev.html
  src/css/webdev.css
Labels: gssoc25, level3, hacktoberfest-accepted

#889 navbar links fixed in about.html
  about.html
Labels: hacktoberfest-accepted

#892 footer links
  about.html
Labels: hacktoberfest-accepted

#894 footer links
  index.html
Labels: hacktoberfest-accepted

#913 extrablank space removed from Contact us page
  index.html
  src/contact.html
Labels: gssoc25, level2, hacktoberfest-accepted

#925 Fix: Improve dark mode visibility for logo and client testimonial text
  .DS_Store
  learn/webdev.html
  src/css/webdev.css
Labels: hacktoberfest-accepted

#919 Fix: add missing Quick Links icons in Digital Marketing page footer (…
  src/digital-marketing.html
Labels: hacktoberfest-accepted

#920 Fix: broken Custom Web Apps icon in Web Development page slider (#915)
  src/web.html
Labels: hacktoberfest-accepted

#921 Fix: add missing text 'Explore' to Content Writing button (#917)
  index.html
Labels: hacktoberfest-accepted

#927 Fix: Apply proper styling to Home page footer (#918)
  index.html
Labels: hacktoberfest-accepted

#945 Redesign index.html Page Layout and Add Login/Signup
  index.html
Labels: gssoc25, level3, hacktoberfest-accepted

#937 Dropdown Toggle In Privacy
  privacy.html
Labels: gssoc25, level3, hacktoberfest-accepted

#924 Add Web Development Blog
  index.html
  src/blogs.js
Labels: gssoc25, level2, hacktoberfest-accepted

#951 Added login button to all pages and removed signup
  about.html
  blogView.html
  index.html
  privacy.html
  sitemap.html
  src/contact.html
  src/digital-marketing.html
  src/faq.html
  src/style.css
  terms.html
  work.html
Labels: gssoc25, level3, hacktoberfest-accepted

#899 Fixed Button Link
  learn/webdev.html
Labels: gssoc25, level1

#904 added scroll to top in contact us page
  src/contact.html
Labels: gssoc25, level2, hacktoberfest-accepted
