Repository gyanshankar1708/GrowCraft, pull requests merged in 2025-09, with the labels that each got.

#390 Fixed :Enhancement of styling of 'Stop Breaches Before They Start' heading under Cyber Analyst page
  src/cyber-analyst.html
Labels: gssoc25, level2

#422 Enhance UI of our work and dix footer of Home page
  index.html
  learn/webdev.html
  src/css/webdev.css
  work.css
  work.html
Labels: gssoc25, level3

#423 update the footer of Cyber analyst page with proper styling
  .vscode/settings.json
  src/cyber-analyst.html
Labels: gssoc25, level2

#426 Contact link fixed in services section
  services.html
Labels: gssoc25, level1

#430 Update work.html with new interactive design
  images/AppDev1.jpeg
  images/BrandingCampaign1.jpeg
  images/EmailMarketing1.jpeg
  images/UIUX1.jpeg
  images/VideoProduction1.jpeg
  images/client1.jpeg
  images/client2.jpeg
  images/client3.jpeg
  images/client4.jpeg
  src/darkMode.js
  work.html
Labels: gssoc25, level3

#431 fixed the overflow
  src/social-media.html
Labels: gssoc25, level1

#429 Fixed : Enhancement of alignment of content under 'Why Choose Our Content Writing Services?' section
  src/content-writing.html
Labels: gssoc25, level2

#450 Navbar font fixed
  index.html
Labels: gssoc25, level2

#441 Redesign the page
  src/contact.html
Labels: gssoc25, level3

#453 Refactored dark mode initialization and updated toggle button icon state
  src/darkMode.js
Labels: gssoc25, level2

#461 Fix : Redesign Footer Section on Services Page with Improved Styling and Accessibility
  services.html
  src/style.css
Labels: gssoc25, level2

#458 Fixed : Improvement of 'Services' page
  services.html
Labels: gssoc25, level1

#486 fix: make logo text visible in navbar in Graphic Designing section
  src/graphic_design.html
Labels: gssoc25, level2

#489 fix: make logo text color visible on web designing page
  src/graphic_design.html
Labels: gssoc25, level1

#508 Fixed the redirection of links
  index.html
  src/content-writing.html
Labels: gssoc25, level1

#400 Added missing footer in about page
  about.html
  index.html
Labels: gssoc25, level2

#525 Fixed text visibility in about us
  index.html
Labels: gssoc25, level2

#532 ReadMore buttons rounded
  index.html
Labels: gssoc25, level2

#534 Cyber Analyst navbar link fixed
  src/cyber-analyst.html
Labels: gssoc25, level2

#536 Home navbar link fixed
  index.html
Labels: gssoc25, level1

#537 Redesigned the social media management page
  src/darkMode.js
  src/social-media-original.html
  src/social-media.html
  src/social-media.html.backup
Labels: gssoc25, level3

#559 The FAQ section does not have a css link included issue resolved
  src/faq.html
Labels: gssoc25, level1

#558 Blog Write Center Aligned
  blogWrite.html
Labels: gssoc25, level2

#563 Add Newsletter Subscription with Toast Notification
  index.html
Labels: gssoc25, level3

#587 Fix: Increase footer logo width for better visibility
  src/contact.html
Labels: gssoc25, level1

#568 Spacing fixes in about us section
  index.html
  src/style.css
Labels: gssoc25, level2

#574 549 our approach layout fix
  about.html
  src/social-media.html
Labels: gssoc25, level3

#575 547 hover effects headings
  about.html
  src/content-writing.html
Labels: gssoc25, level2

#585 replaced old twitter icon
  about.html
Labels: gssoc25, level1

#608 Fixed ReadMore width in Services Section
  index.html
Labels: gssoc25, level2

#644 fix: corrected the social media icons
  src/social-media.html
Labels: gssoc25, level2

#662 Unify Blog Page Header & Footer with Homepage Design for Consistency
  blogListing.html
Labels: gssoc25, level2

#697 Feedback area text limit added
  index.html
Labels: gssoc25, level2

#703 removed extra footer from contact us page
  src/contact.html
Labels: gssoc25, level2

#665 fix: duplicate footer
  about.html
Labels: gssoc25, level2

#708 footer color and alignment issue fixed
  src/contact.html
Labels: gssoc25, level2

#676 improved UI and made social media icons visible
  src/components/footer.html
Labels: gssoc25, level2

#706 Added Careers Page
  careers.html
  src/components/footer.html
Labels: gssoc25, level3

#712 [Bug Fix] Style footer for Content Writing page
  src/content-writing.html
Labels: gssoc25, level2

#724 Dot slider fixed in web dev page
  src/web.html
Labels: gssoc25, level3

#730 Improve About Us section layout: icons above titles & spacing fix
  index.html
  work.html
Labels: gssoc25, level1

#689 Enhance the contentWriting page
  learn/contentWriting.css
  learn/contentwriting.html
  src/components/footer.html
Labels: gssoc25, level3

#720 Fixed the FAQ page
  src/faq.html
Labels: gssoc25, level3

#740 [BUG FIX] fixed the footer links on webdevelopment page
  src/web.html
Labels: gssoc25, level1

#744 fix(services-section): unify icon colors and improve card layout
  index.html
Labels: gssoc25, level2

#745 feat(training-section): improve layout, add tagline, and unify card styles
  index.html
Labels: gssoc25, level2

#783 favicon added in faq page
  src/faq.html
Labels: gssoc25, level1

#785 AboutUs Link now working in FAQ page
  src/faq.html
Labels: gssoc25, level1

#786 ContactUs link now working in faq page
  src/faq.html
Labels: gssoc25, level1

#791 home tab now working in faq page
  src/faq.html
Labels: gssoc25, level1

#792 OurWork tab now working in faq page
  src/faq.html
Labels: gssoc25, level1
